env:
  CIRRUS_CLONE_DEPTH: 3 # The internal git client reads CIRRUS_CLONE_DEPTH.
  MAKEFLAGS: '-j 2' # The build VMs currently have two CPU cores.
  IGNORE_OSVERSION: yes

task:
  freebsd_instance:
    image_family: $IMAGE_FAMILY
  allow_failures: $IMAGE_FAMILY == "freebsd-13-0-snap" # currently broken
  env:
    matrix:
      - IMAGE_FAMILY: freebsd-11-3-snap
      - IMAGE_FAMILY: freebsd-12-1-snap
      - IMAGE_FAMILY: freebsd-13-0-snap
  script:
    - freebsd-version
    - pkg update -f
    - pkg install -qy git autoconf
    - (cd .. && git clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet git://github.com/the-tcpdump-group/libpcap.git && cd libpcap && ./configure --prefix=/tmp && make -s)
    - touch .devel
    - ./configure --prefix=/tmp
    - make -s CFLAGS=-Werror all
    - make check
    - make install
    - make releasetar
